//expected to pass a test
fun main() {
    val exception = KotlinNullPointerException("test")
    throw exception
}